server: 
  port: 9191
  
spring:
  datasource:

    url: jdbc:mysql://localhost:3306/projet?serverTimezone=UTC&useLegacyDatetimeCode=false

    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
